language: ruby
sudo: false
 
rvm:
  - 2.2.3
 
bundler_args: --without development --deployment
 
cache: bundler
 
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
 
script:
  - bundle exec rake test
